version: '3'
services:
  backend:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    networks:
      - mr_network
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - mr_network
    command: mongod

volumes:
  mongodb-data:

networks:
  mr_network:
    external: true
